language: csharp
mono: none
dotnet: 2.1.300
script:
 - dotnet build
 - dotnet test Trees.Tests
before_install:
 - docker build -f Dockerfile.ninmemapi . --tag artsdatabanken/ninmemapi
 - docker build -f Dockerfile.datapreprocessing . --tag artsdatabanken/ninmemapi_datapreprocessing
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
