language: csharp
mono: none
dotnet: 2.1.105
script:
 - dotnet restore
 - dotnet build
 - dotnet test Trees.Tests
deploy:
  provider: releases
  file_glob: true
  file: NinMemApi/bin/*
  skip_cleanup: true
  on:
    tags: true