language: csharp
mono: none
dotnet: 2.1.105
script:
 - dotnet restore
 - dotnet build
 - dotnet test Trees.Tests
 - dotnet publish
deploy:
 - provider: pages
   local-dir: NinMemApi/bin/netcoreapp2.0/
   skip-cleanup: true
   github-token: $GITHUB_API_KEY  # Set in the settings page of your repository, as a secure variable
   keep-history: false
