language: csharp
mono: none
dotnet: 2.1.300
script:
 - dotnet build
 - dotnet test Trees.Tests
before_install:
 - docker build --tag artsdatabanken/ninmemapi .
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
